# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('fabricant', models.CharField(max_length=50)),
                ('port_quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
