language: python

python:
  - 3.5

services: postgresql

env:
  - DJANGO=1.11.4

install:
  - pip install -r requirements.txt

script:
  - flake8
  - coverage run manage.py test

after_success:
  - coveralls
