language: python

python:
  - 3.5

services: postgresql

env:
  - DJANGO=1.11.4

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - flake8
  - coverage run manage.py test

after_success:
  - coveralls

deploy:
  provider: heroku
  api_key: 2324c521-1c19-43c1-bf2d-8e7bd925630a
  on:
    tags: true
