# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dgo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cableLength', models.FloatField()),
                ('dgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgo.GOD')),
            ],
        ),
    ]
