# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_reserve', '0002_technicalreserve_infrastructure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalreserve',
            name='infrastructure',
        ),
        migrations.AddField(
            model_name='technicalreserve',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
