# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 01:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(
                    max_length=15,
                    validators=[django.core.validators.RegexValidator(
                        message="""Phone number must be entered in the format:
                        '+999999999'. Up\n            to 15 digits allowed.""",
                        regex='^\\+?1?\\d{8,15}$')])),
                ('email', models.CharField(
                    max_length=40,
                    validators=[django.core.validators.EmailValidator()])),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='contact_type', to='contact.ContactType'),
        ),
    ]
