# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20170920_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contact_type', to='contact.ContactType'),
        ),
    ]
