# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ipaType', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ipa', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('institution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipa.InstitutionType')),
            ],
        ),
    ]
