# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutiontype',
            name='id_ipaType',
        ),
        migrations.RemoveField(
            model_name='participantinstitution',
            name='id_ipa',
        ),
    ]
