# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutiontype',
            old_name='id_ipaType',
            new_name='id_type',
        ),
    ]
