# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa', '0002_auto_20170916_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutiontype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='participantinstitution',
            name='id',
        ),
        migrations.AlterField(
            model_name='institutiontype',
            name='id_type',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participantinstitution',
            name='id_ipa',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
