# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipa', '0003_auto_20170919_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutiontype',
            old_name='id_type',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='participantinstitution',
            old_name='id_ipa',
            new_name='id',
        ),
    ]
