# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa', '0004_auto_20170919_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutiontype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='participantinstitution',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
