# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmendationBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('designNumber', models.IntegerField()),
                ('access_box', models.BooleanField()),
                ('creation_date', models.DateField()),
                ('extinction_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmendationBoxStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmendationBoxType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
           model_name='emendationbox',
           name='emendation_structure',
           field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='emendation_box.EmendationBoxStructure'
                                   ),
        ),
        migrations.AddField(
           model_name='emendationbox',
           name='emendation_type',
           field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='emendation_box.EmendationBoxType'),
        ),
    ]
