# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emendation_box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emendationbox',
            name='extinction_date',
            field=models.DateField(blank=True),
        ),
    ]
