# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UndergroundBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.IntegerField()),
                ('box_type', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('cover_type', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('removed_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('draw_number', models.IntegerField()),
            ],
        ),
    ]
