# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('underground_box', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UndergroundBoxType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='undergroundbox',
            name='box_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='underground_box.UndergroundBoxType'),
        ),
    ]
