# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uplink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_vlan', models.CharField(max_length=50)),
                ('band', models.FloatField()),
                ('code', models.IntegerField()),
            ],
        ),
    ]
