# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 21:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uplink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uplink',
            name='code',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
