# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uplink', '0003_auto_20170923_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uplink',
            name='code',
            field=models.IntegerField(),
        ),
    ]
